version: "2.4"
services:
  smb-simulator:
    build: .
    image: ie-smb-sim:latest
    ports:
      - "6969:5000"
    mem_limit: 500mb
    networks:
            - proxy-redirect
networks:
    proxy-redirect:
        external:
            name: proxy-redirect
        driver: bridge